### ISSUE TITLE
More than one event marker? 

### ISSUE THREAD

**Issue by mgbleichner** [lrkrol/SEREEGA#13]
This is a great toolbox. Thanks for that.
Is there a way to add more than one event marker per trial?  I do have several subevents taking place within one trial and would  like to add all of them.

**Comment by lrkrol** [comment]
Thanks, Martin, also for opening this issue!

Were you thinking of events with a fixed timing relative to the "main" event (the zero point as set by SEREEGA), or with a variable latency depending on the deviations/shifts of the various signals?

There currently is no way of adding more than one event marker using SEREEGA itself, but it should be relatively easy to add some once everything is in EEGLAB format, provided we're talking about fixed latencies. For random latencies, we may have to first address issue #4, and then use that output to add markers.

**Comment by mgbleichner** [comment]
Indeed, I was thinking about events with a fixed timing relative to the main event. I.e. I want to model the response in relation to a sequence of sounds within a single trial, do it would be nice to have an event for each tone. I solved it for now by adding events afterwards.

**Comment by lrkrol** [comment]
Yes, that is how I would do it too: just adding the events afterwards. Alternatively it could be indicated in the epoch configuration struct where the main marker is set, but that does not seem to make a lot of sense since epochs are really defined around just that single marker. 

I've now uploaded [`utl_add_markers_toeeglabdataset`](../blob/master/utils/utl_add_markers_toeeglabdataset.m) to the current master branch to add new markers relative to existing markers in epoched EEGLAB datasets. 

Would that solve the issue?
