### ISSUE TITLE
Parallellize `generate_scalpdata`

### ISSUE THREAD

**Issue by arnevdk** [lrkrol/SEREEGA#14]
Nice simulation tool! I would like to use it, but long simulation times are holding me back a bit.
Using a parallell for loop for generating epochs or components in `generate_scalpdata` can significantly speed up simulation.

**Comment by lrkrol** [comment]
Thanks for this excellent suggestion. I had not considered parallel processing before, but the switch turned out to be rather easy. The newly committed `generate_scalpdata` in the development branch should now make use of a parallel loop where available (additionally relying on `utl_show_progress_timetocomplete` and `utl_show_progress_parfor` to provide progress updates). Please let me know if this works for you!
