### ISSUE TITLE
#Add-on Request: SSVEP Class

### ISSUE THREAD

**Issue by vpKumaravel** [lrkrol/SEREEGA#16]
Hello,

It is a great job. Thanks for this tool. Do you perhaps have ideas to create SSVEP simulated data, as well?

Thanks,
Velu

**Comment by lrkrol** [comment]
Hi Velu, I would certainly like to support this, but since I have not worked with SSVEP data myself, I am unsure what exactly would be needed. SSVEP experiments, I believe, do not necessarily have 'events' of the kind SEREEGA currently uses as the core structure of the data. Aside from that, though, to the extent that SSVEP elicits oscillatory activity, you can, of course, use the ERSP class to generate these ollications and their harmonics. That would simulate the main effect as I understand it. Otherwise, please let me know what would be needed to simulate SSVEP data, and we'll see what we can do!

**Comment by vpKumaravel** [comment]
Hi Laurens,

Thanks for the response and I think ERSP is closely related to SSVEP as you suggested. My advisor (who is an expert in SSVEP stimulations), however, told me that it depends on the bandwidth (broad- or narrow- band) of the signal. From what I observed in my initial attempts, I see that ERSP class produces a narrowband (therefore, SSVEP) signal. In my opinion, this can be already a workaround.

Another approach that I considered is to use the 5th class i.e., using pre-generated time series and I succeeded in producing what I wanted using your toolbox. This indeed proves the extensibility of your work. Great job, again. :-) 

Perhaps, in future, when I am more relaxed I hope to create a class for SSVEP and show you the code. 

Best wishes,
Velu
